name: "Code style"

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        required: true

      levels:
        description: |
          Codestyle grading levels.
        type: string
        required: true

      tidy-config:
        description: |
          Clang-tidy configuration.
        type: string
        required: true

      timeout:
        description: |
          Timeout in minutes before the workflow is failed.
        type: number
        default: 3

      cmake-flags:
        description: |
          Additional cmake flags.
        type: string
        default: ""

    outputs:
      results:
        value: ${{ jobs.codestyle.outputs.results }}
      config:
        value: ${{ inputs.levels }}

jobs:
  codestyle:
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: ${{ inputs.timeout }}
    name: Codestyle

    outputs:
      results: ${{ steps.output.outputs.results }}
      verdict: ${{ steps.output.outputs.verdict }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Generate build system
        run: |
          cmake \
            -B /tmp/cicd/build \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            ${{ inputs.cmake-flags }}

      - name: Run clang-tidy
        env:
          TIDY_CONFIG: ${{ inputs.tidy-config }}
        run: |
          echo "$TIDY_CONFIG" > /tmp/cicd/tidy-config.yml

          run-clang-tidy-19 \
            -p /tmp/cicd/build \
            -config-file=/tmp/cicd/tidy-config.yml \
            -header-filter=. \
            -exclude-header-filter='^\/tmp\/cicd\/build\/' \
            -source-filter='^(?!\/tmp\/cicd\/build\/).*$' \
            -export-fixes /tmp/cicd/tidy-fixes.yml || true

          echo '# tidy-fixes.yml'
          cat /tmp/cicd/tidy-fixes.yml

      - name: Show cool diagnostics
        id: output
        env:
          LEVELS: ${{ inputs.levels }}
        shell: 'python3 {0}'
        run: |
          import bisect
          import os.path
          import yaml
          from dataclasses import dataclass, field
          from pathlib import Path

          from gha_helper import gh


          @dataclass
          class PositionMap:
            _files_offsets: dict = field(default_factory=dict)

            def _get_offsets(self, path: Path):
              if path in self._files_offsets:
                return self._files_offsets[path]

              with path.open('rb') as f:
                data = f.read()

              offsets = [0] + [i for i, c in enumerate(data, 1) if c == ord('\n')]
              self._files_offsets[path] = offsets

              return offsets

            def get_line_col(self, path: Path, offset: int):
              offsets = self._get_offsets(path)

              line_idx = bisect.bisect_right(offsets, offset) - 1
              line_start = offsets[line_idx]

              line, column = line_idx + 1, offset - line_start + 1

              return line, column


          def process_diagnostics(diagnostics: Path, root: Path):
            root = Path(os.path.abspath(root))

            with open(diagnostics, "r", encoding="utf-8") as f:
              data = yaml.safe_load(f)

            if data is None:
              data = {}

            posmap = PositionMap()
            seen = set()
            total_warnings = 0

            for diagnostic in data.get("Diagnostics", []):
              name = diagnostic["DiagnosticName"]
              level = diagnostic["DiagnosticName"]
              message = diagnostic["DiagnosticMessage"]["Message"]
              path = diagnostic["DiagnosticMessage"]["FilePath"]
              offset = diagnostic["DiagnosticMessage"]["FileOffset"]

              if path == "":
                continue

              # Use os.path.abspath because pathlib doesn't normalize .. out
              path = Path(os.path.abspath(path))

              key = (path, name, offset)
              if key in seen:
                continue
              seen.add(key)

              line, col = posmap.get_line_col(path, offset)

              try:
                file = path.relative_to(root)
              except ValueError:
                continue

              if level == "Error":
                gh.annotation.error(message, file=file, line=line, col=col)
              else:
                gh.annotation.warning(message, file=file, line=line, col=col)

              total_warnings += 1

            required_warns = gh.input.get_json("LEVELS")[0]
            verdict = "pass" if total_warnings < required_warns else "fail"

            print("\nVerdict:", verdict)

            gh.output.save("verdict", verdict)
            gh.output.save_json("results", {
              "total_warnings": total_warnings,
            })

          process_diagnostics(Path("/tmp/cicd/tidy-fixes.yml"), Path("."))

      - name: Fail the workflow
        if: ${{ steps.output.outputs.verdict != 'pass' }}
        run: exit 1
