name: "Coverage"

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        required: true

      levels:
        description: |
          Coverage grading levels.
        type: string
        required: true

      timeout:
        description: |
          Timeout in minutes before the workflow is failed.
        type: number
        default: 3

      cmake-flags:
        description: |
          Additional cmake flags.
        type: string
        default: ""

    outputs:
      results:
        value: ${{ jobs.coverage.outputs.results }}
      config:
        value: ${{ inputs.levels }}

jobs:
  coverage:
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: ${{ inputs.timeout }}
    name: Coverage

    outputs:
      results: ${{ steps.output.outputs.results }}
      verdict: ${{ steps.output.outputs.verdict }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Generate build system
        run: |
          cmake \
            -B /tmp/cicd/build \
            -DCMAKE_BUILD_TYPE=Debug \
            -DWITH_COVERAGE=ON \
            -DNO_COVERAGE_HTML=ON \
            ${{ inputs.cmake-flags }}

      - name: Build tests
        run: |
          cmake \
            --build /tmp/cicd/build \
            --parallel "${JOBS:-1}"

      - name: Check coverage
        run: |
          export CTEST_PARALLEL_LEVEL="${JOBS:-1}"
          cmake \
            --build /tmp/cicd/build \
            --target coverage

      - name: Show coverage log
        run: |
          cat /tmp/cicd/build/coverage.txt

      - name: Save output
        id: output
        if: ${{ always() }}
        env:
          LEVELS: ${{ inputs.levels }}
        shell: 'python3 {0}'
        run: |
          import json
          from gha_helper import gh

          levels = gh.input.get_json("LEVELS")

          try:
            with open("/tmp/cicd/build/coverage.json") as f:
              coverage = json.load(f)

            with open("/tmp/cicd/build/coverage.txt") as f:
              coverage_log = f.read()

            percent = coverage["line_percent"]
            verdict = "pass" if percent >= levels[1] else "fail"

            print(f"\nCoverage: {percent}%")
            print(f"Verdict: {verdict}")

            gh.output.save("verdict", verdict)
            gh.output.save_json("results", {
              "ran": True,
              "percent": percent,
              "log": coverage_log,
            })
          except FileNotFoundError:
            print("\nVerdict: fail (coverage did not run)")
            gh.output.save("verdict", "fail")

            gh.output.save_json("results", {
              "ran": False
            })

      - name: Fail the workflow
        if: ${{ steps.output.outputs.verdict != 'pass' }}
        run: exit 1
