name: "Report"

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        required: true

      data:
        description: |
          Stringified JSON object, containing configs and results from all modules.
        type: string
        required: true

jobs:
  summary:
    name: Summary
    runs-on: ${{ inputs.runs-on }}
    if: ${{ !cancelled() }}
    permissions:
      pull-requests: write
    steps:
      - name: Generate summary
        id: summary
        env:
          DATA: ${{ inputs.data }}

          # Actually, this is the time of the last push across ALL branches.
          # It doesn't matter for our usecase, since it (should) always be >= than the actual branch push time.
          #
          # So, if you forgot to open a PR and missed a deadline -- you've brought this upon yourself.
          PUSHED_AT: ${{ github.event.pull_request.head.repo.pushed_at }}
          COMMIT: ${{ github.event.pull_request.head.sha }}
        shell: 'python3 {0}'
        run: |
          import json
          from collections import defaultdict
          from dataclasses import dataclass
          from typing import TypedDict, Any
          from zoneinfo import ZoneInfo

          from gha_helper import gh, md


          @dataclass
          class ModuleData:
            config: dict[str, Any]
            results: dict[str, Any]

          def json_loads_or(s: str, default: dict = None) -> dict:
            if default is None:
              default = {}
            try:
              return json.loads(s) if s else default
            except json.JSONDecodeError:
              return default

          needs_context = json.loads(gh.input.get("DATA"))

          modules: dict[str, ModuleData] = {}
          for name, data in needs_context.items():
            modules[name] = ModuleData(
              config=json_loads_or(data.get("outputs", {}).get("config")),
              results=json_loads_or(data.get("outputs", {}).get("results")),
            )

          def grade(value, levels, results):
            *results, default = results
            pairs = list(zip(levels, results))

            if levels[0] < levels[-1]:
              pairs = reversed(pairs)

            for threshold, result in pairs:
              if value >= threshold:
                return result

            return default


          ########################## GENERATE SUMMARY ##########################

          def render_overview(modules):
            if len(modules) == 0:
              md.raw("- Automated checks are disabled for this labwork.")

            if (tests := modules.get("tests")) is not None:
              if not tests.results:
                md.raw("- Tests: Critically failed 💀")
              else:
                build_only = all(t["build_only"] for t in tests.results)
                if build_only:
                  all_built = all(t["built"] for t in tests.results)
                  if all_built:
                    md.raw("- All platforms built successfully ✅🎉")
                  else:
                    md.raw("- Some of the platforms failed to build ❌")
                else:
                  all_passed = all(t["all_passed"] for t in tests.results)
                  if all_passed:
                    md.raw("- All tests passed successfully ✅🎉")
                  else:
                    md.raw("- Some of the tests had failed ❌")

            if (codestyle := modules.get("codestyle")) is not None:
              if not codestyle.results:
                md.raw("- Code style: Critically failed 💀")
              else:
                n_warnings = codestyle.results.get("total_warnings", -1)
                codestyle_text = grade(n_warnings, codestyle.config, [
                  "- Code style is not followed ❌",
                  "- Code style is followed ⚠️",
                  "- Code style is followed ✅",
                  "- Code style is followed ⭐️",
                  "- Code style is ??? 💀",
                ])
                plural = 's' if n_warnings != 1 else ''
                md.raw(f"{codestyle_text} ({n_warnings} warning{plural})")

            if (coverage := modules.get("coverage")) is not None:
              if not coverage.results:
                md.raw("- Code coverage: Critically failed 💀")
              else:
                if coverage.results.get("ran"):
                  percent = coverage.results.get("percent", -1)
                  emoji = grade(percent, coverage.config, ["❌", "⚠️", "✅", "⭐️", "💀"])
                  md.raw(f"- Code coverage: {percent}% {emoji}")
                else:
                  md.raw("- Code coverage: Failed to run 💀")

            md.raw()


          def render_test_matrix(modules):
            if (tests := modules.get("tests")) is None:
              return

            if not tests.results:
              return

            platform_names = {p["id"]: p["name_html"] for p in tests.config}
            tests_data = {t["id"]: t for t in tests.results}

            d = defaultdict(lambda: defaultdict(lambda: defaultdict(list)))
            for platform in tests_data.values():
              for test, status in platform.get("tests", {}).items():
                if '.' in test:
                  suite, name = test.split(".", 1)
                else:
                  suite, name = "*Unknown Suite*", test

                d[suite][platform["id"]][status].append(name)

            md.raw("### Test matrix")

            table = [["", "№ Passed", *platform_names.values()]]

            table.append(["*Built?*", ""])
            for pid in platform_names.keys():
              if tests_data[pid]["built"]:
                table[-1].append("✅")
              else:
                table[-1].append("❌")

            for suite, platforms in d.items():
              suite = suite.removesuffix("Suite")
              table.append([f"**{suite}**"])

              failed = set(sum((p["failed"] for p in platforms.values()), []))
              passed = set(sum((p["passed"] for p in platforms.values()), []))

              n_total = len(failed | passed)
              n_passed = n_total - len(failed)

              table[-1].append(f"`{n_passed}/{n_total}`")

              for pid in platform_names.keys():
                if not tests_data[pid]["ran"]:
                  table[-1].append("💀")
                else:
                  if len(platforms[pid]["failed"]) > 0:
                    table[-1].append("❌")
                  else:
                    table[-1].append("✅")

            md.table(table)


          def render_time_footer():
            pushed_at = gh.input.get_timestamp("PUSHED_AT") \
              .astimezone(ZoneInfo("Europe/Moscow")) \
              .strftime('%Y-%m-%d %H:%M:%S %Z%z')

            commit = gh.input.get("COMMIT")[:7]
            md.raw(f"*This report was generated for the commit* `{commit}` *pushed on* `{pushed_at}`.")


          md.raw("# 📊 Report Card")
          md.raw()
          md.raw("### Overview")
          md.raw()

          render_overview(modules)
          render_test_matrix(modules)
          render_time_footer()

      - name: Post summary
        run: cat SUMMARY.md >> "$GITHUB_STEP_SUMMARY"

      - name: Send report card to pull request
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc  # v2.8.2
        with:
          refresh-message-position: true
          message-path: SUMMARY.md
